// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimescaleDataProcessor.Api.Data.Context;

#nullable disable

namespace TimescaleDataProcessor.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimescaleDataProcessor.Api.Entities.IntegralResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgExecutionTime")
                        .HasColumnType("double precision")
                        .HasComment("Среднее время выполнения операции в секундах");

                    b.Property<double>("AvgIndicator")
                        .HasColumnType("double precision")
                        .HasComment("Среднее значение показателя");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Имя файла, из которого получен интегральный результат");

                    b.Property<double>("MaxIndicator")
                        .HasColumnType("double precision")
                        .HasComment("Максимальное значение показателя");

                    b.Property<double>("MedianIndicator")
                        .HasColumnType("double precision")
                        .HasComment("Медианное значение показателя");

                    b.Property<double>("MinIndicator")
                        .HasColumnType("double precision")
                        .HasComment("Минимальное значение показателя");

                    b.Property<DateTime>("MinStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Минимальное время начала операции в формате UTC");

                    b.Property<double>("TimeDeltaInSeconds")
                        .HasColumnType("double precision")
                        .HasComment("Дельта времени StartTime в секундах");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("TimescaleDataProcessor.Api.Entities.ValueRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("double precision")
                        .HasComment("Время выполнения операции в секундах");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Имя файла, из которого было получено значение операции");

                    b.Property<double>("Indicator")
                        .HasColumnType("double precision")
                        .HasComment("Значение показателя");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Время начала операции в формате UTC");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.ToTable("Values", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
